FROM node:14.15.1

WORKDIR /home/node/app

CMD [ "npm", "run", "start:dev" ]

# 빌드 명령어
# docker build -t realworld-f-img:dev -f ./Dockerfile.dev .

# 이미지 실행 명령어
# docker run --name realworld-f-con-dev -v $(pwd):/home/node/app -p 80:80 realworld-f-img:dev